label vanguard-flight-computer
  kernel /boot/zImage
  devicetree /boot/vanguard_stm32h743.dtb
  append console=ttySTM0,115200 root=/dev/mmcblk0p1 rw rootfstype=ext2 rootwait earlyprintk consoleblank=0 ignore_loglevel
